import {
  Activity,
  BrainCircuit,
  AlertTriangle,
  TrendingUp,
  ShieldAlert,
} from "lucide-react";

const insights = [
  {
    icon: <TrendingUp size={22} />,
    title: "Traffic Prediction",
    description:
      "West Delhi congestion expected to increase by 18% during evening peak hours.",
    color: "text-blue-400",
    bg: "bg-blue-500/10",
  },
  {
    icon: <AlertTriangle size={22} />,
    title: "High-Risk Zone",
    description:
      "Illegal parking hotspot detected near Tilak Nagar requiring immediate enforcement.",
    color: "text-orange-400",
    bg: "bg-orange-500/10",
  },
  {
    icon: <ShieldAlert size={22} />,
    title: "Public Safety Alert",
    description:
      "Women's safety incident flagged for rapid response and increased patrol allocation.",
    color: "text-red-400",
    bg: "bg-red-500/10",
  },
  {
    icon: <BrainCircuit size={22} />,
    title: "AI Recommendation",
    description:
      "Garbage complaints decreased by 12%. Current collection strategy is performing efficiently.",
    color: "text-green-400",
    bg: "bg-green-500/10",
  },
];

export default function LiveInsights() {
  return (
    <section className="mx-auto mt-20 max-w-7xl px-8">

      <div className="rounded-3xl border border-zinc-800 bg-zinc-900/70 p-8 backdrop-blur-md">

        <div className="mb-8 flex items-center gap-3">

          <Activity
            className="text-green-400"
            size={30}
          />

          <div>

            <h2 className="text-3xl font-bold">
              Live AI Intelligence
            </h2>

            <p className="text-zinc-400">
              Real-time insights generated by the CivicIQ Decision Engine
            </p>

          </div>

        </div>

        <div className="grid gap-6 lg:grid-cols-2">

          {insights.map((item) => (

            <div
              key={item.title}
              className="rounded-2xl border border-zinc-800 bg-black/50 p-6 transition-all duration-300 hover:-translate-y-1 hover:border-blue-500"
            >

              <div className="flex items-start gap-4">

                <div
                  className={`rounded-2xl p-3 ${item.bg} ${item.color}`}
                >
                  {item.icon}
                </div>

                <div>

                  <h3 className="text-xl font-bold">
                    {item.title}
                  </h3>

                  <p className="mt-2 leading-7 text-zinc-400">
                    {item.description}
                  </p>

                </div>

              </div>

            </div>

          ))}

        </div>

      </div>

    </section>
  );
}